### ISSUE TITLE
Using property="sort.skip" interferes with skipping the sort pom plugin

### ISSUE THREAD

**Issue by wappers** [Ekryd/echo-maven-plugin#3]
https://github.com/Ekryd/echo-maven-plugin/blob/b810727c20769b0b5c18df603806faa8174cff1c/maven-plugin/src/main/java/echo/EchoMojo.java#L103

Using property="sort.skip" interferes with skipping the sort pom plugin. Should this be echo.skip?

**Comment by Ekryd** [comment]
You are quite right. I will fix this as soon as possible.

**Comment by Ekryd** [comment]
Started the development of a new release. The code already contains the switch from 'sort.skip' to 'echo.skip'. 

I will add some integration tests and look at Sonar warnings before making the release.

**Comment by Ekryd** [comment]
Tests are added and warnings are fixed.
Could you please try the plugin before I do an official release of it.

Download the latest version of the plugin.
Compile it using 'mvn clean install'
Use it by trying 'mvn com.github.ekryd.echo-maven-plugin:echo-maven-plugin:1.2.1-SNAPSHOT:echo -Decho.message="No strings attached" -Decho.skip' or use the snapshot version in your pom file.

**Comment by wappers** [comment]
Works for me, also using `mvn com.github.ekryd.echo-maven-plugin:echo-maven-plugin:1.2.1-SNAPSHOT:echo -Decho.message="No strings attached" -Dsort.skip` outputs

```
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 3 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 3 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] Echo plugin parent                                                 [pom]
[INFO] Echo output                                                        [jar]
[INFO] Echo Maven plugin                                         [maven-plugin]
[INFO]
[INFO] -----------< com.github.ekryd.echo-maven-plugin:echo-plugin >-----------
[INFO] Building Echo plugin parent 1.2.1-SNAPSHOT                         [1/3]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- echo-maven-plugin:1.2.1-SNAPSHOT:echo (default-cli) @ echo-plugin ---
[INFO] No strings attached
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Echo plugin parent 1.2.1-SNAPSHOT .................. SUCCESS [  0.605 s]
[INFO] Echo output ........................................ SKIPPED
[INFO] Echo Maven plugin 1.2.1-SNAPSHOT ................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.746 s
[INFO] Finished at: 2020-02-18T14:03:52Z
[INFO] ------------------------------------------------------------------------
```

There is one problem on my system (windows) this test in TestFromFile could be updated to use URL path, fails with error 

```
Argument(s) are different! Wanted:
pluginLog.debug(
    "Reading input from C:\dev\github\echo-maven-plugin\echo\target\test-classes\messageText.txt"
);
-> at echo.TestFromFile.foundFileInClassPathShouldOutputReadingLocation(TestFromFile.java:105)
Actual invocation has different arguments:
pluginLog.debug(
    "Reading input from /C:/dev/github/echo-maven-plugin/echo/target/test-classes/messageText.txt"
);
-> at echo.util.FileUtil.getFileFromRelativeOrClassPath(FileUtil.java:121)

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at echo.TestFromFile.foundFileInClassPathShouldOutputReadingLocation(TestFromFile.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)


```

```
    @Test
    public void foundFileInClassPathShouldOutputReadingLocation() throws MalformedURLException {
        PluginParameters parameters = new PluginParametersBuilder().setMessage(null, "messageText.txt").createPluginParameters();
        EchoPlugin echoPlugin = new EchoPlugin(pluginLog, parameters, echoOutput);
        echoPlugin.echo();

        String absolutePath = new File("target/test-classes/messageText.txt").toURI().toURL().getPath();
        verify(pluginLog).debug("Reading input from " + absolutePath);
    }
```

**Comment by Ekryd** [comment]
Thanks!
I will do a quick fix of the test before release. Most likely during this weekend.

**Comment by Ekryd** [comment]
A new version, 1.3.0, of the echo plugin is released. I hope that you enjoy it. 
Kind regards
/Björn
